### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by ch01ca** [PythonForForex/Interactive-brokers-python-api-guide#1]
unhandled exception in EReader thread
Traceback (most recent call last):
  File "/.local/lib/python3.7/site-packages/ibapi/reader.py", line 34, in run
    data = self.conn.recvMsg()
  File "local/lib/python3.7/site-packages/ibapi/connection.py", line 99, in recvMsg
    buf = self._recvAllMsg()
  File "/.local/lib/python3.7/site-packages/ibapi/connection.py", line 119, in _recvAllMsg
    buf = self.socket.recv(4096)
OSError: [Errno 9] Bad file descriptor

**Comment by PythonForForex** [comment]
This looks like the issue discussed in the article under common errors. Have you tried updating the [connection.py](https://github.com/PythonForForex/Interactive-brokers-python-api-guide/blob/master/Common%20Errors/connection.py) file in your **ibapi** folder? There is a copy in the code base under the common errors folder.

More details here --> https://algotrading101.com/learn/interactive-brokers-python-api-native-guide/#common-errors-with-ib-python-native-api-v976

Please let me know if replacing the connection.py file works

**Comment by cero1010** [comment]
That works awesome. Thanks!

**Comment by ch01ca** [comment]
thank you for prompt reply.
I replaced the file at ibapi folder and now no errors. 

however, the process just exit after printing a few bars

**Comment by PythonForForex** [comment]
Great! good to hear that resolved your problem.

I see you've opened another issue for the exit, I'll address it there.
