### ISSUE TITLE
Empty DataFrame 

### ISSUE THREAD

**Issue by ch01ca** [PythonForForex/Interactive-brokers-python-api-guide#2]
python store_hourly_candles_EURUSD.py
ERROR 1 504 Not connected
Empty DataFrame
Columns: [DateTime, Close]
Index: []

**Comment by PythonForForex** [comment]
The error message shows you are not connected.

Check to make sure you are using the correct port number and that you've allowed API connection from within TWS or Gateway (whichever you are using).

If that doesn't resolve it then try and change the client id. It might not be accepting new connections if a prior connection was terminated unexpectedly.
