### ISSUE TITLE
Watchlist

### ISSUE THREAD

**Issue by 87TR** [PythonForForex/Interactive-brokers-python-api-guide#3]
Hi Jignesh. Thank you so much for putting all this useful information on github. I've been doing a lot of googling and can't seem to find a solution where I can take a snapshot of the last/open/high/low price for stocks in my watchlist. I use your sample code to pull this information one stock at a time (loop for tickers in a CSV file) but it's pretty long. I am following about 100 tickers and it takes about 3 seconds per ticker to get the data so my information is never synchronized. Any idea how to request the last/open/high/low price for multiple stocks in a single request? Many thanks in advance.

**Comment by PythonForForex** [comment]
Certain snapshot requests have built-in delays. Have you tried just opening a stream? It may seem less efficient than requests for snapshots but the API could be throttling your requests if there are too many within a certain period.

There is an example on the blog to open a stream for live data and then storing that data into a Pandas DataFrame. From there you can resample your data to the timeframe that you need.

**Comment by 87TR** [comment]
Ok, many thanks. I will try that.

**Comment by david03kimo** [comment]
Is it possible to show the example of resample the dataframe to other timeframe?Feel struggle to consolidate stream data or bars to 3 min K for example.

**Comment by PythonForForex** [comment]
df.resample('3min').agg({'open': 'first', 'high': 'max', 'low': 'min', 'close': 'last'})

You can try the above command if you're resampling from 1min to 3min.
This assumes you are using **open**, **high**, **low**, **close** as your column names

**Comment by david03kimo** [comment]
It works,many thanks.
And thanks for your step by step article about IB API.
