### ISSUE TITLE
Error: cannot create or remove files in install directory

### ISSUE THREAD

**Issue by gian9302** [PythonForForex/Interactive-brokers-python-api-guide#4]
when running python3 setup.py install I'm getting the error in the subject with 
[Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-62392.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\Lib\site-packages\

how do I sort this out?
thx

**Comment by PythonForForex** [comment]
This looks like a permission issue. Are you running from command prompt or from within your IDE?

Try running it from the command prompt - but when launching the command prompt right click on it and choose "run as admnistrator"

**Comment by gian9302** [comment]
> This looks like a permission issue. Are you running from command prompt or from within your IDE?
> 
> Try running it from the command prompt - but when launching the command prompt right click on it and choose "run as admnistrator"
